/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package farmingsystem.view;

import farmingsystem.FarmingConnection;
import farmingsystem.controller.ComplainImpl;
import farmingsystem.model.Complain;
import farmingsystem.controller.UserImp;
import farmingsystem.model.User;

import java.io.ObjectInputFilter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author FPALES
 */
public final class ComplainDialog extends javax.swing.JDialog {

    /**
     * Creates new form ComplainDialog
     */
    public ComplainDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        initComponents();
        Load();
        LoadUserID();
    }
    public final void Load()
    {
        ComplainImpl complain = new ComplainImpl();
        List<Complain> list = complain.list();
        DefaultTableModel DFT = (DefaultTableModel) jTable4.getModel();
        DFT.setRowCount(0);
        for(Complain complains: list)
        {
            int id = complains.getId();
            String ticketNo  = complains.getTicketNo();
            int orderId = complains.getOrderId();
            String message = complains.getMessage();
            String status = complains.getStatus();
            String dateCreated = complains.getDateCreated();
            String dateResolve = complains.getDateResolved();
            int responseId = complains.getResponse_id();
            String response = complains.getResponse();
            int user = complains.getUser_id();
            DFT.addRow(new Object[]{id,ticketNo,orderId,message,status,dateCreated,dateResolve,responseId,response,user});
        }    
  
    }
    public void LoadUserID(){
        try {
            Connection con = FarmingConnection.getConnection();
            String sql = "SELECT id FROM users";
            PreparedStatement ps = con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            jcUseId.removeAllItems();
            while(rs.next()){
               
                
                jcUseId.addItem(rs.getString(1));
            }
            
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error");
        }
        
    }
//    public void LoadComplainId(){
//        try {
//            Connection con = FarmingConnection.getConnection();
//            String sql = "SELECT id FROM complain";
//            PreparedStatement ps = con.prepareStatement(sql);
//            ResultSet rs = ps.executeQuery();
//            userIDchoice.removeAllItems();
//            while(rs.next()){
//               
//                
//                complainIdChoice.addItem(rs.getString(1));
//            }
//            
//        } catch (Exception e) {
//            e.printStackTrace();
//            JOptionPane.showMessageDialog(null, "Error");
//        }
//        
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooser1 = new com.raven.datechooser.DateChooser();
        jPanel2 = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnRemoveComplain = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtMessage = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtMessage1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jcStatus = new javax.swing.JComboBox<>();
        lbldateCreated = new javax.swing.JLabel();
        lbldateResolve = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jcUseId = new javax.swing.JComboBox<>();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        user = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnSelect = new javax.swing.JButton();
        lbluser = new javax.swing.JLabel();
        statusComboBox = new javax.swing.JComboBox<>();
        lblticket = new javax.swing.JLabel();
        btnStatusFailed = new javax.swing.JButton();
        btnStatusDone = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnSave.setBackground(new java.awt.Color(0, 204, 255));
        btnSave.setText("save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(0, 255, 51));
        btnUpdate.setText("update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnRemoveComplain.setBackground(new java.awt.Color(255, 51, 0));
        btnRemoveComplain.setText("remove");
        btnRemoveComplain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveComplainActionPerformed(evt);
            }
        });

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "complain_id", "ticket_no", "order_id", "message", "image", "status", "date_created", "date_resolve", "category_type", "null"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable3);
        if (jTable3.getColumnModel().getColumnCount() > 0) {
            jTable3.getColumnModel().getColumn(0).setResizable(false);
            jTable3.getColumnModel().getColumn(1).setResizable(false);
            jTable3.getColumnModel().getColumn(2).setResizable(false);
            jTable3.getColumnModel().getColumn(3).setResizable(false);
            jTable3.getColumnModel().getColumn(4).setResizable(false);
            jTable3.getColumnModel().getColumn(5).setResizable(false);
            jTable3.getColumnModel().getColumn(6).setResizable(false);
            jTable3.getColumnModel().getColumn(7).setResizable(false);
            jTable3.getColumnModel().getColumn(8).setResizable(false);
            jTable3.getColumnModel().getColumn(9).setResizable(false);
        }

        txtMessage.setColumns(20);
        txtMessage.setRows(5);
        jScrollPane3.setViewportView(txtMessage);

        txtMessage1.setColumns(20);
        txtMessage1.setRows(5);
        jScrollPane5.setViewportView(txtMessage1);

        jLabel2.setText("user");

        jLabel3.setText("Message");

        jLabel4.setText("Order ID");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jcStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Done", "Pending", "Failed", " " }));
        jcStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcStatusActionPerformed(evt);
            }
        });

        lbldateCreated.setText("Date Created");

        lbldateResolve.setText("Date Resolved");

        jLabel7.setText("Status");

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "ticket_no", "order_id", "message", "status", "date_created", "date_resolve", "response_id", "response", "user_id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane7.setViewportView(jTable4);

        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });

        btnSearch.setText("search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jLabel1.setText("Response");

        btnSelect.setBackground(new java.awt.Color(255, 255, 0));
        btnSelect.setText("select");
        btnSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectActionPerformed(evt);
            }
        });

        lbluser.setText("User");

        statusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Done", "Failed", " " }));
        statusComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusComboBoxActionPerformed(evt);
            }
        });

        lblticket.setText("ticket No");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane3)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jcUseId, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lbldateCreated, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lbldateResolve, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(167, 167, 167))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(btnSave)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnUpdate)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnSelect)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnRemoveComplain))
                                            .addComponent(lbluser, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(101, 101, 101)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jcStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnSearch))))
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(statusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblticket, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1)
                        .addGap(140, 140, 140)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearch))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(6, 6, 6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lbluser))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(statusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbldateCreated)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbldateResolve)
                                .addGap(31, 31, 31)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnUpdate)
                                    .addComponent(btnSave)
                                    .addComponent(btnSelect)
                                    .addComponent(btnRemoveComplain)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jcUseId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblticket))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addGap(3, 3, 3)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );

        btnStatusFailed.setBackground(new java.awt.Color(255, 255, 255));
        btnStatusFailed.setForeground(new java.awt.Color(255, 0, 0));
        btnStatusFailed.setText("Failed");
        btnStatusFailed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatusFailedActionPerformed(evt);
            }
        });

        btnStatusDone.setBackground(new java.awt.Color(255, 255, 255));
        btnStatusDone.setForeground(new java.awt.Color(51, 51, 255));
        btnStatusDone.setText("Done");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(btnStatusFailed)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnStatusDone)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStatusFailed)
                    .addComponent(btnStatusDone))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        
         Complain complain = new Complain();
          
          
          String message = txtMessage.getText(); 
          /// get Ticket No
          int length = 10;
          String lower_case = "qwertyuiopasdfghjklzxcvbnm";
          String upper_case = "QWERTYUIOPASDFGHJKLZXCVBNM";
          String genTicket="";
          for (int i = 0; i< length; i++){
              int rand = (int)(3*Math.random());
              switch (rand) {
                  case 0:
                      genTicket += String.valueOf((int)(0* Math.random()));
                      break;
                  case 1:
                      rand = (int)(lower_case.length() * Math.random());
                      genTicket += String.valueOf((lower_case.charAt(rand)));
                      break;
                  case 2:
                      rand = (int)(upper_case.length() * Math.random());
                      genTicket += String.valueOf((upper_case.charAt(rand)));
                      break;
                  default:
                      throw new AssertionError();
              }
          }
        String ticketNo = genTicket;         
       // String status = String.valueOf(jcStatus.getSelectedItem());
        String status ="Pending";
        String created = String.valueOf(LocalDateTime.now());
        int responseId=1;
        String response = "";
        int user = Integer.parseInt( String.valueOf(jcUseId.getSelectedItem()));
        
        
//        String resolve="";
//        if (status.equalsIgnoreCase("Done") || status.equalsIgnoreCase("Failed")){
//        resolve = String.valueOf(LocalDateTime.now());    
//        }
//        else if(status.equalsIgnoreCase("Pending")){
//        
//        }
//        lbldateCreated.setText(created);
//        lbldateResolve.setText(resolve);
        
        //setters
        
        complain.setMessage(message);
        complain.setTicketNo(ticketNo);
        complain.setStatus(status);
        complain.setDateCreated(created);
//        complain.setDateResolved(resolve);
        complain.setResponse_id(responseId);
        complain.setResponse(response);
        complain.setUser_id(user);
     
        
        // to be deleted
        System.out.println("ComplainId : "+complain.getMessage()+"\n");
        System.out.println("userID : "+complain.getMessage()+"\n");
        System.out.println("message    :"+complain.getMessage()+"\n");
        System.out.println("ticketNo   :"+complain.getTicketNo()+"\n");
        System.out.println("status     :"+complain.getStatus()+"\n");
        System.out.println("deytCretid :"+complain.getDateCreated()+"\n");
        System.out.println("deytReculb :"+complain.getDateResolved()+"\n");
        System.out.println("response :"+complain.getResponse()+"\n");
        System.out.println("response ID :"+complain.getResponse_id()+"\n");
        System.out.println("user :"+complain.getUser_id()+"\n");
        
        // delete on top only (it is for testing)
        
        
        ComplainImpl complainImpl = new ComplainImpl();
        complainImpl.addComplain(complain);
        Load();
        
        txtMessage.setText("");
        jcStatus.setSelectedItem("");   
        lbldateCreated.setText("");
        lbldateResolve.setText("");        
        txtMessage.requestFocus();
        
        
    }//GEN-LAST:event_btnSaveActionPerformed
  
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        Complain complain = new Complain();

        String edtmessage = txtMessage.getText(); 
        String upstatus = String.valueOf(statusComboBox.getSelectedItem());
        String edtresolve = String.valueOf(LocalDateTime.now());
//            // status condition
//            if (statusComboBox.equals("Done"))
//            {
//            edtresolve = String.valueOf(LocalDateTime.now());    
//            }
//            else if(statusComboBox.equals("Failed"))
//            {
//            edtresolve = String.valueOf(LocalDateTime.now());    
//            }
//            else{
//            edtresolve ="none";    
//            }
        // Complain set
        complain.setUser_id(Integer.parseInt(String.valueOf(jcUseId.getSelectedItem())));
        complain.setTicketNo(lblticket.getText());
        complain.setMessage(edtmessage);
        complain.setStatus(upstatus);
        complain.setDateResolved(edtresolve);
        complain.setDateCreated(lbldateCreated.getText());

        // query complain imp
        ComplainImpl complainImpl = new ComplainImpl();
        complainImpl.addComplain(complain);
        Load();
        
        txtMessage.setText("");
        jcStatus.setSelectedItem("");   
        lbldateResolve.setText("");        
        txtMessage.requestFocus();
        
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnRemoveComplainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveComplainActionPerformed
        Complain complain = new Complain();
        complain.setTicketNo(String.valueOf(lblticket.getText()));
        ComplainImpl complainImpl = new ComplainImpl();
        complainImpl.deleteComplain(complain);
        Load();
       
        txtMessage.setText("");
        lblticket.setText("");
        statusComboBox.setSelectedItem("");   
        lbldateCreated.setText("");
        lbldateResolve.setText("");
        txtMessage.requestFocus();
        

    }//GEN-LAST:event_btnRemoveComplainActionPerformed

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userActionPerformed
    int search;
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        int user_id=Integer.parseInt(user.getText());
        String statuses = String.valueOf(jcStatus.getSelectedItem());
        
        // query
        ComplainImpl complainImpl = new ComplainImpl();
        List<Complain> list = complainImpl.searchComplain(user_id, statuses);
        DefaultTableModel DFT = (DefaultTableModel) jTable4.getModel();
        DFT.setRowCount(0);
        
        for(Complain complains: list)
        {
            int id = complains.getId();
            String ticketNo  = complains.getTicketNo();
            int orderId = complains.getOrderId();
            String message = complains.getMessage();
            String status = complains.getStatus();
            String dateCreated = complains.getDateCreated();
            String dateResolve = complains.getDateResolved();
            int responseId = complains.getResponse_id();
            String response = complains.getResponse();
            int user = complains.getUser_id();

            DFT.addRow(new Object[]{id,ticketNo,orderId,message,status,dateCreated,dateResolve,responseId,response, user_id});
        }    
        
        
        
    }//GEN-LAST:event_btnSearchActionPerformed

    private void jcStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcStatusActionPerformed
        // TODO add your handling code here:
       
        String searchStatus = String.valueOf(jcStatus.getSelectedItem());
        ComplainImpl complainImpl = new ComplainImpl();
        List<Complain> list = complainImpl.searchComplainByStatus(searchStatus);
        DefaultTableModel DFT = (DefaultTableModel) jTable4.getModel();
        DFT.setRowCount(0);
        for(Complain complains: list)
        {
            int id = complains.getId();
            String ticketNo  = complains.getTicketNo();
            int orderId = complains.getOrderId();
            String message = complains.getMessage();
            String status = complains.getStatus();
            String dateCreated = complains.getDateCreated();
            String dateResolve = complains.getDateResolved();
            int responseId = complains.getResponse_id();
            String response = complains.getResponse();
            int user = complains.getUser_id();
            DFT.addRow(new Object[]{id,ticketNo,orderId,message,status,dateCreated,dateResolve,responseId,response,user});
        }    
    }//GEN-LAST:event_jcStatusActionPerformed

    private void btnStatusFailedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatusFailedActionPerformed
        
    }//GEN-LAST:event_btnStatusFailedActionPerformed
    int select;
    private void btnSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectActionPerformed
        select = Integer.parseInt(JOptionPane.showInputDialog("Enter Complain ID"));
       
        ComplainImpl complainimpl = new ComplainImpl();
        Complain complain  = complainimpl.get(select);
        
        
        lbluser.setText(String.valueOf(complain.getId()));
        txtMessage.setText(complain.getMessage());
        lblticket.setText(complain.getTicketNo());
        lbldateCreated.setText(complain.getDateCreated());
        lbldateResolve.setText(complain.getDateResolved());
        
        
    }//GEN-LAST:event_btnSelectActionPerformed

    private void statusComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComplainDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComplainDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComplainDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComplainDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ComplainDialog dialog = new ComplainDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRemoveComplain;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSelect;
    private javax.swing.JButton btnStatusDone;
    private javax.swing.JButton btnStatusFailed;
    private javax.swing.JButton btnUpdate;
    private com.raven.datechooser.DateChooser dateChooser1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JComboBox<String> jcStatus;
    private javax.swing.JComboBox<String> jcUseId;
    private javax.swing.JLabel lbldateCreated;
    private javax.swing.JLabel lbldateResolve;
    private javax.swing.JLabel lblticket;
    private javax.swing.JLabel lbluser;
    private javax.swing.JComboBox<String> statusComboBox;
    private javax.swing.JTextArea txtMessage;
    private javax.swing.JTextArea txtMessage1;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
