/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package farmingsystem.view;

import farmingsystem.controller.UserImp;
import farmingsystem.model.User;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MY-PC
 */
public class UserViewAllUser extends javax.swing.JFrame {

    /**
     * Creates new form ViewUsers
     */
    public UserViewAllUser() {
        initComponents();
        AllUsers();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        buttonSupplier1 = new javax.swing.JButton();
        buttonSupplier = new javax.swing.JButton();
        buttonFarmer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "username", "password", "first_name", "middle_name", "last_name", "gender", "birthday", "contact_number", "house_no", "city_address", "profile_image", "valid_id", "email", "user_type", "active", "user_id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Byte.class, java.lang.Byte.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, false, true, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        buttonSupplier1.setText("All Users");
        buttonSupplier1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSupplier1ActionPerformed(evt);
            }
        });

        buttonSupplier.setText("Suppliers");
        buttonSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSupplierActionPerformed(evt);
            }
        });

        buttonFarmer.setText("Farmers");
        buttonFarmer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFarmerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonFarmer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonSupplier)
                .addGap(18, 18, 18)
                .addComponent(buttonSupplier1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonFarmer)
                    .addComponent(buttonSupplier)
                    .addComponent(buttonSupplier1))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1290, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 440));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSupplier1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSupplier1ActionPerformed
       initComponents();
        AllUsers();
    }//GEN-LAST:event_buttonSupplier1ActionPerformed

    private void buttonSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSupplierActionPerformed
      initComponents();
     Supliers();
    }//GEN-LAST:event_buttonSupplierActionPerformed

    private void buttonFarmerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFarmerActionPerformed

        initComponents();
        Farmers();

    }//GEN-LAST:event_buttonFarmerActionPerformed

    public void AllUsers(){
        UserImp dao = new UserImp();
        List<User> list = dao.list();
        DefaultTableModel DFT = (DefaultTableModel) jTable1.getModel();
         DFT.setRowCount(0);
         for(User us: list)
        {
            int id = us.getId();
            String username = us.getUsername();
            String password = us.getPassword();
            
             String firstName = us.getFirstName();
             String middleName = us.getMiddleName();
             String lastName = us.getLastName();
             
              String birthDate = us.getBirthDate();
              String contactNumber = us.getContactNumber();
              String houseNo = us.getHouseNo();
              String streetAddress = us.getStreetAddress();
              String cityAddress= us.getCityAddress();
              
             // byte profileImage = us.getProfielImage();
             
            
             String email = us.getEmail();
             String userType = us.getUserType();
             boolean active = us.getActive();
             String userId = us.getUserId();
             
            
            
            DFT.addRow(new Object[]{id,username,password,firstName,middleName,lastName
            ,birthDate,contactNumber,houseNo,streetAddress,cityAddress,"[binary data]","[binary data]",email,
            userType,active,userId});
        }   
        
    }
    
     public void Farmers(){
        UserImp dao = new UserImp();
        List<User> list = dao.list();
        DefaultTableModel DFT = (DefaultTableModel) jTable1.getModel();
         DFT.setRowCount(0);
         for(User us: list)
        {
            if("Farmer".equals(us.getUserType())){
            int id = us.getId();
            String username = us.getUsername();
            String password = us.getPassword();
            
             String firstName = us.getFirstName();
             String middleName = us.getMiddleName();
             String lastName = us.getLastName();
             
              String birthDate = us.getBirthDate();
              String contactNumber = us.getContactNumber();
              String houseNo = us.getHouseNo();
              String streetAddress = us.getStreetAddress();
              String cityAddress= us.getCityAddress();
              
             // byte profileImage = us.getProfielImage();
             
            
             String email = us.getEmail();
             String userType = us.getUserType();
             boolean active = us.getActive();
             String userId = us.getUserId();
             
            DFT.addRow(new Object[]{id,username,password,firstName,middleName,lastName
            ,birthDate,contactNumber,houseNo,streetAddress,cityAddress,"[binary data]","[binary data]",email,
            userType,active,userId});
            }
        }     
    }
     
     
         public void Supliers(){
        UserImp dao = new UserImp();
        List<User> list = dao.list();
        DefaultTableModel DFT = (DefaultTableModel) jTable1.getModel();
         DFT.setRowCount(0);
         for(User us: list)
        {
            if("Supplier/Wholesaler".equals(us.getUserType())){
            int id = us.getId();
            String username = us.getUsername();
            String password = us.getPassword();
            
             String firstName = us.getFirstName();
             String middleName = us.getMiddleName();
             String lastName = us.getLastName();
             
              String birthDate = us.getBirthDate();
              String contactNumber = us.getContactNumber();
              String houseNo = us.getHouseNo();
              String streetAddress = us.getStreetAddress();
              String cityAddress= us.getCityAddress();
              
             // byte profileImage = us.getProfielImage();
             
            
             String email = us.getEmail();
             String userType = us.getUserType();
             boolean active = us.getActive();
             String userId = us.getUserId();
             
            
            
            DFT.addRow(new Object[]{id,username,password,firstName,middleName,lastName
            ,birthDate,contactNumber,houseNo,streetAddress,cityAddress,"[binary data]","[binary data]",email,
            userType,active,userId});
            }
        }   
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserViewAllUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserViewAllUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserViewAllUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserViewAllUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserViewAllUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonFarmer;
    private javax.swing.JButton buttonSupplier;
    private javax.swing.JButton buttonSupplier1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
